#!/usr/bin/env bash
# script to transfer a file from client to server
# accepts 4 params (filepath, IP of server, username & path for ssh priv key)

if [ "$#" -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
