#!/usr/bin/env bash
# script to redirect 301 to a given url

echo "Updating system"
sudo apt-get update
echo "running installation of nginx"
sudo apt-get install -y nginx
echo "allowing access on port 80 only"
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
echo "changing system owner permissions"
sudo chown -R ubuntu /vaw/www
echo "creating html page with string"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "redirecting url link"
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "restarting nginx"
sudo service nginx restart
