#!/usr/bin/env bash
# bash script to install nginx on my web server and redirect to a page

sudo apt-get update
sudo apt-get install -y nginx

sudo tee /etc/nginx/sites-available/redirect_me <<EOL
server {
	listen 80;

	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}
EOL
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Restart Nginx to apply changes
sudo service nginx restart
