#!/usr/bin/env bash
# script that creates a custom 404 error page 

echo "Updating system"
sudo apt-get update
echo "running installation of nginx"
sudo apt-get install -y nginx
echo "allowing access on port 80"
sudo ufw allow 'Nginx HTTP'
echo "changing system owner permissions"
sudo chown -R ubuntu /var/www
echo "creating html page with string"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "redirecting url link"
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Creating custom 404 error page"
echo "Ceci n'est pas une page" >> /var/www/html/custom_404.html
sudo sed -i '25i\       error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
echo "Restarting nginx"
sudo service nginx restart
