#!/usr/bin/env bash
#A bash script that pings an IP address passed as an arument
if [[ $1 == ^[0-9]{1.3}\.[0-9]{1.3}\.[0-9]{1.3}\.[0-9]{1.3}$ ]]; 
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
